In [ ]:
#ML Zoom Camp
#Introduction Numpy Library

In [1]:
#import numply library
import numpy as np

In [2]:
#creating arrays
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 3.7)
#10 is length of array, and 3.7 is a value of array

array([3.7, 3.7, 3.7, 3.7, 3.7, 3.7, 3.7, 3.7, 3.7, 3.7])

In [5]:
val = [1,2,3,5,7,12]
val
#data type list of python

[1, 2, 3, 5, 7, 12]

In [6]:
#converted to array using numpy
numpy_array = np.array(val)
numpy_array

array([ 1,  2,  3,  5,  7, 12])

In [7]:
#get the element of array, indexing array starts from 0
#get the 4th element of array [numpy_array]
numpy_array[3]

5

In [8]:
#change the values of 4th element
numpy_array[3] = 8
numpy_array

array([ 1,  2,  3,  8,  7, 12])

In [9]:
#create a range number, range number start from 0
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#if we want the value starts from 3, then code
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [11]:
#linspace, create the number from first parameter as START to second parameter as STOP, and the third parameter as LENGTH of ARRAY
np.linspace(0, 1, 8)


array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

In [ ]:
#MULTIDIMENSIONAL ARRAY

In [12]:
#first parameter as ROWS, second parameter as COLOUMNS
np.zeros((5 , 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
numpy_array_multidimentional = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
])
numpy_array_multidimentional

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
#get the element of array
numpy_array_multidimentional[0, 2]

3

In [16]:
#get the value in entire row in spesific row
numpy_array_multidimentional[2]

array([7, 8, 9])

In [18]:
#change the value in row 3
numpy_array_multidimentional[2] = [17, 18, 19]
numpy_array_multidimentional

array([[ 1,  2, 19],
       [ 4,  5,  6],
       [17, 18, 19]])

In [19]:
#get entire coloumn in specific coloumn
numpy_array_multidimentional[:, 1]

array([ 2,  5, 18])

In [22]:
numpy_array_multidimentional[:]

array([[ 1,  2, 19],
       [ 4,  5,  6],
       [17, 18, 19]])

In [23]:
numpy_array_multidimentional[:, 2] = [10, 11, 12]

In [24]:
numpy_array_multidimentional

array([[ 1,  2, 10],
       [ 4,  5, 11],
       [17, 18, 12]])

In [21]:
numpy_array_multidimentional[0,2]

19

In [ ]:
#Randomly Generated Arrays

In [25]:
np.random.rand(5, 2)

array([[0.08876737, 0.89535178],
       [0.59509987, 0.08455797],
       [0.95109359, 0.09707595],
       [0.80682475, 0.82192314],
       [0.38231389, 0.72761012]])

In [26]:
#if we want get the integer value
np.random.randint(low=0, high=100, size=(5, 2))

array([[80,  2],
       [65, 65],
       [11, 17],
       [53, 78],
       [ 7, 82]])

In [ ]:
#ELEMENT WISE OPERATIONS

In [32]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [33]:
#if we want to add value for each number in array, we can create the code like below
a + 2

array([2, 3, 4, 5, 6])

In [34]:
#we can do multiply, divided and substraction
a * 2


array([0, 2, 4, 6, 8])

In [35]:
a / 2

array([0. , 0.5, 1. , 1.5, 2. ])

In [36]:
a - 3
#since we do not save the operation before, so the value that substraction is the first value that was we assigned to the variable a

array([-3, -2, -1,  0,  1])

In [37]:
b = (10 + (a * 2)) ** 2
b

array([100, 144, 196, 256, 324], dtype=int32)

In [38]:
a

array([0, 1, 2, 3, 4])

In [39]:
a + b

array([100, 145, 198, 259, 328])

In [ ]:
#COMPARISON OPERATIONS

In [40]:
a

array([0, 1, 2, 3, 4])

In [41]:
a >= 3

array([False, False, False,  True,  True])

In [42]:
b

array([100, 144, 196, 256, 324], dtype=int32)

In [43]:
a > b

array([False, False, False, False, False])

In [44]:
a != b

array([ True,  True,  True,  True,  True])

In [45]:
a [a > (b / 100)]
#show all the value of array a that the value of a  more than b / 100

array([2, 3, 4])

In [ ]:
#SUMMARIZING OPERATIONS

In [46]:
a

array([0, 1, 2, 3, 4])

In [47]:
a.min()

0

In [48]:
a.max()

4

In [49]:
a.sum()

10

In [50]:
a.mean()

2.0

In [51]:
a.std()

1.4142135623730951

In [ ]:
#for multidimensional array

In [52]:
numpy_array_multidimentional

array([[ 1,  2, 10],
       [ 4,  5, 11],
       [17, 18, 12]])

In [53]:
numpy_array_multidimentional.sum()

80

In [54]:
numpy_array_multidimentional.mean()

8.88888888888889

In [56]:
numpy_array_multidimentional.min()

1

In [55]:
numpy_array_multidimentional.max()

18