In [1]:
import numpy as np

In [ ]:
#Vector Operations
#in linear algebra, vector in coloumns but when use numpy the vector shows in row

In [2]:
u = np.array([2, 4, 5, 6])
u

array([2, 4, 5, 6])

In [3]:
#multiply vector with number
2 * u

array([ 4,  8, 10, 12])

In [4]:
v = np.array([1, 0, 0, 2])
v

array([1, 0, 0, 2])

In [5]:
u + v

array([3, 4, 5, 8])

In [11]:
#MULTIPLICATION VECTOR WITH VECTOR (DOT PRODUCT)
print('size array of u ->', u.shape[0])
print('size array of v ->',v.shape[0])
#since these are array one dimentional or vector

size array of u -> 4
size array of v -> 4


In [14]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0] #check if the size of vector u equals to vector v

    n = u.shape[0] #rows of vector u
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]

    return result

vector_vector_multiplication(u, v)

#assert -> 
#syntac Python Python evaluates the accompanying expression, which is hopefully true. 
#If the expression is false, Python raises an AssertionError exception

14.0

In [15]:
#in numpy we can use as same as with the function code
u.dot(v)

14

In [16]:
U = np.array([
    [2, 4, 5, 6], 
    [1, 2, 1, 2], 
    [3, 1, 2, 1]])
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [29]:
U.shape

(3, 4)

In [25]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]
    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

matrix_vector_multiplication(U, v)
    

array([14.,  5.,  5.])

In [26]:
U.dot(v)

array([14,  5,  5])

In [31]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]
])
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [28]:
V.shape

(3, 4)

In [33]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0] #check row of U equals to coloumn of V

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    #concern in coloumns V, because in function matrix_vector_multiplication we have multiplied the matrix U, with vector v, that only one coloumn
    #on matrix multplication, we can use the same function, but we multiplied the function into each coloumn of matrix V
    for i in range(num_cols):
        Vi = V[:, i]
        UVi = matrix_vector_multiplication(U, Vi)
        result[:, i] = UVi 
    
    return result

matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [34]:
#in numpy,
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [35]:
#IDENTITY MATRIX
np.eye(5) #fill with the dimension matrix we want

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [39]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [ ]:
#INVERSE MATRIX
#why we need inverse? because matrix can not be divided
#inverse must be SQUARE MATRIX
#it will be usefull in Linear Regression

In [41]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [45]:
Vs = V[0:3]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [46]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [47]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
Vs.dot(Vs_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
V.T #transpose

array([[1. , 0. , 0. , 2. ],
       [1. , 0.5, 2. , 1. ],
       [2. , 1. , 1. , 0. ]])